### ISSUE TITLE
第七条的疑问

### ISSUE THREAD

**Issue by ziofat** [taowen/12fallacy#1]
> VII. 服务好每一个用户。目前服务了100万人，刚融完资，即将服务1000万人，对应的研发团队至少得提前扩充10倍

这个存疑，服务好每一个用户，似乎首先应当扩充的是客服团队。10 倍的用户规模并不代表会带来 10 倍的需求和 10 倍的缺陷，为什么要扩充 10 倍研发团队呢？

**Comment by lucifer1004** [comment]
@ziofat 你再看一下这个仓库的名字`12fallacy`，中文名字只是个反讽。
